### ISSUE TITLE
Please add for arm64 (aarch64) architecture

### ISSUE THREAD

**Issue by jarbelix** [jfut/nginx-module-fancyindex-rpm#7]
With the growing use of the arm architecture (https://blogs.oracle.com/cloud-infrastructure/post/why-arm-based-application-development-is-best-on-oracle-linux-in-oracle-cloud-infrastructure), I installed **AlmaLinux 9 arm64** on OCI and would like to be able to install this package.

From what I saw in the downloads, they are only available for the **x86_64** architecture.

**Comment by jfut** [comment]
Thank you for the suggestion. I've also been using arm64 instances on OCI and have been wanting to support them someday.
I've created builds that support arm64 as indicated below. You can download and try them out from the Artifacts.
https://github.com/jfut/nginx-module-fancyindex-rpm/actions/runs/8027185569

Since the old release workflow is broken, I plan to fix it and release it with a new tag version.

**Comment by jfut** [comment]
We have released v0.5.2-5, which includes the aarch64 version!
